### ISSUE TITLE
Доклад: Почему Angular зло или как писать на Angular после React

### ISSUE THREAD

**Issue by sovetkin-am** [AngularPiter/Talks#3]
1.  **Переопределять глобальные объекты плохо**

- Object.prototype.toString
- Promise.name === ?

2. **Как писать быстрый код**

- Следи за изменениями руками

3. **Какая проблема с Angular-way разработчиками**

4. **Как писать на Angular так же, как на React**

- Redux в Angular
- Изучай Javascript

**Comment by splincode** [comment]
Можно закрыть issue
