### ISSUE TITLE
Коварные улыбки или не ангуляром единым

### ISSUE THREAD

**Issue by lekzd** [AngularPiter/Talks#4]
Emoji прочно вошли в современный веб, но так ли просто реализовать поддержку смайликов в приложении, как это может показаться на первый взгляд? Это история о поиске решений когда реализация angular-way тормозит и фреймворк не может предоставить оптимальных инструментов для быстрой работы маленького компонента.

**Comment by splincode** [comment]
Можно закрыть issue
